arnog/mathlive

- src/addons/outputSpokenText.js
Hopefully simple enough that I got this right...
> added speech for crossouts

- src/addons/outputAST.js
- src/addons/outputMathML.js
changes 'let' to 'const' to remove warnings
> Fix two warnings in src/addons

- src/addons/auto-render.js
I thought I had added this before, but probably messed up my branching/pull request.
This changes the speech for AT from a text string to MathML so it will (hopefully) be better.
> Static mathml

- src/mathlive.js
Set value of 'marks' so it doesn't use value from parent env
> Fix problem with highlighting not working after a change

- examples/speech/index.html
- examples/speech/index.js
- examples/vue/index.html
- src/addons/outputSpokenText.js
- src/editor/editor-mathfield.js
- src/editor/editor-shortcuts.js
- src/mathlive.js
- tutorials/SELECTORS.md
- tutorials/USAGE_GUIDE.md
> Speak long a

- examples/speech/index.html
Docs are updated along with a small bug fix.
> Speech doc update

- src/addons/outputMathML.js
- src/addons/outputSpokenText.js
- src/editor/editor-mathfield.js
Mainly fixed up bug(s) that caused SSML to leak into aria-live regions (I wish they would deal with that, but that's not the way screen readers work now).
Also fixed a bug where <mi> was generated when <mn> should have been generated for MathML.
> Spoken ssml with highlighting

- src/editor/editor-mathfield.js
This makes `MathFieldCallback`s much more useful.
> Add parameter type to MathFieldCallback

- src/editor/editor-mathfield.js
> Fix performWithFeedback_ focus

- src/addons/outputMathML.js
- src/editor/editor-mathfield.js
Tied for least important commit :-)
Added fix for #276. No longer least important commit...
> Fix typo on comment

- src/math-json/latex/definitions-arithmetic.ts
A little typo sneaked in there
> fix: change multiply trigger to \\cdot

- src/editor/virtual-keyboard-utils.ts
> Fix keyboard event listener removal

- src/editor/virtual-keyboard-utils.ts
Fix unexpected exception with `undefined` object access when user starts typing with hidden virtual keyboard
> Fix issue with `undefined` object access

- src/core/span.ts
single space was missing, making data-* not work at all.
> fix for cssData

- jest.config.js
- test/__mocks__/styleMock.js
- test/latex.test.ts
- test/markup.test.ts
- test/math-ascii.test.ts
fix broken imports and mock stylesheet imports
in order to make tests be able to run again
> test: make tests run again

- src/vue-mathlive.js
feat: vue-mathlive support vue 3.x
> feat: vue-mathlive support vue 3.x

- src/core-definitions/enclose.ts
The border box didn't display.
> Fix : roundedbox not displaying #1300

- css/core.less
- examples/rendering/index.html
Even with WebRender enabled on Firefox, the issue still happened sometimes. Moving the translate solves this issue:
relates to #934
> fix: Fixed #934 by moving translate css

- src/editor-model/commands.ts
Not sure if this is the way you would have liked this implemented, but nevertheless here it is.
A matrix to test on:
`\begin{bmatrix}a & bbbbb \\ c & dddd \\ e & fff\end{bmatrix}`
I have a few questions regarding the code which I hope you could assist.
```
// doesn't highlight
let newSelection: Selection;
if (targetSelection < left) {
// extending selection upwards
newSelection = {
ranges: [[targetSelection, right]],
direction: 'backward'
};
} else {
// reducing selection upwards
newSelection = {
ranges: [[left, targetSelection]],
direction: 'forward'
};
}
model.setSelection(newSelection);
```
This code ends up not highlighting the selection, and if you look at the selection details it's only updating the "Position" value - it gets corrected when you hold shift to continue your selection …
> feat: allow navigation of ArrayAtom with up and down keys

- src/editor/undo.ts
> Undo/Redo emits 'input' event

- src/core-atoms/leftright.ts
- src/editor-mathfield/mode-editor-math.ts
- src/editor-model/delete.ts
- keep leftright atom if one of its delimiters is removed.
- only hoist body if both delimiters are removed.
> Enhance delete & insert delims in leftright atom

- src/editor-model/commands.ts
Same as #1639 but works with fractions (and anything else with an above/below?)
I hadn't considered the other else if branch of vertical movement - but conveniently `branch` is also an array of atoms so I can apply the same logic to an upper/lower branch as a matrix cell.
Tested with this LaTeX:
```
\begin{aligned}\frac{100000000000000000}{\sqrt{1x2y3z}+x+y+z} & =a \\ aaaaaaaaaaaaaaaaa & =b \\ bbbbbbbbbbbbbbb & =c\end{aligned}
```
> feat: make vertical navigation of fractions and matrices the same

- src/core-atoms/array.ts
- src/editor-model/array.ts
- src/editor/keybindings-definitions.ts
> feat: Add matrix editing shortcuts

- src/core-atoms/line.ts
- src/editor/atom-to-speakable-text.ts
This Pull request adds some more symbols to the latex to speakable text conversion.
> Added support for more symbols (latex2speech)

- src/editor-mathfield/mathfield-private.ts
> fix #1884, dangerously setting prompt content

- src/editor-mathfield/mathfield-private.ts
> make setPromptContent suppression behave as expected

- src/editor-mathfield/keyboard-input.ts
Commit 9165550 broke custom `mathModeSpace`, this change gets it working again.
> fix: repair mathModeSpace

- src/public/mathfield-element.ts
- src/public/mathfield.ts
getPromptValue() can now use output formats
> half fixed #1985 : add format to getPromptValue

- src/core-definitions/mhchem.ts
fix `ChemAtom` type in mhchem.ts
> fix: ChemAtom type

- src/editor/suggestion-popover.ts
Fix: https://github.com/arnog/mathlive/issues/2669
> Fix suggestion popover insert bug

- src/editor-model/model-private.ts
- src/editor/default-menu.ts
- src/editor/l10n-strings.ts
- src/formats/atom-to-typst.ts
- src/public/core-types.ts
- test/smoke/index.html
This enables people to run `getValue("typst")`.
While this does not work for 100% of the cases, I think it's a good start.
Thanks: @galchapman.
> added get value typst format

- src/latex-commands/definitions-utils.ts
* fix #2740 
* fix #2743 
* fix #2744
> fix: `\iff`, `\Coloneqq`, `\hArr`
