css/mathlive.core.less
src/addons/auto-render.js
src/addons/outputSpokenText.js
src/editor/editor-shortcuts.js
src/mathlive.js

Correct logic for inlineShortcuts override. Fixes #23.
Big change (I think included in this) is the addition of code to make static math read with AT. I've tested it with NVDA. This change adds a span around the mathlive output. It uses aria-hidden on this span. It adds a sibling node that is the text to speak (should be MathML at some point in the future for better accessibility). This is visually hidden, but it is what screen readers see. Fixes #25.
I also tweaked the speech slightly based on NVDA speaking '.'s.

Accessibility

---

docs/tutorial-MASTON.html

`mathml` was listed as \`mathml\' and as a result did not appear in `code` tags, unlike the rest of the optional keys listed in the MASTON docs.

Fixed mathml not being in code tags.

---

docs/addons_maston.js.html
docs/tutorial-CONTRIBUTOR_GUIDE.html
docs/tutorial-USAGE_GUIDE.html
src/addons/maston.js
tutorials/CONTRIBUTOR_GUIDE.md
tutorials/USAGE_GUIDE.md

Fixed some minor typos/issues in the documentation:
- jsperf.com has a URL listed but no functioning link.
- stand-alone expressions described as 'stand-along'
- MASTON parseExpression claiming to return a MathML string, when it actually returns an AST object.

Fix minor docs typos

---

docs/mathlive.js.html
docs/module-mathlive.html
src/mathlive.js

Added documentation for the `latexToAST` and `latexToMathML` functions.
This is assuming that the intended return type for `latexToAST` is in fact `Object` (its current return type) and not `string` as the docs previously stated.

Add function docs

---

css/mathlive.core.less

This occurs when math field isn't directly in main container

Fix unappropriate position of ML_popover

---

examples/virtual_keyboard/index.html
src/editor/editor-virtualKeyboard.js

**lisp-case** props are represented by **camelCase** in JSON
New JSON example:
```
{
"class": "",
"insert": "",
"key": "",
"latex": "",
"aside": "",
"altKeys": "",
"shifted": "",
"shiftedCommand": "",
"command": "",
"label": ""
}
```

added missed JSON property's mapping.

---

package.json

A recent update to the package made it fail to install because the engine for Node became specified as the latest Node major version. This PR just changes that requirement to allow the 10.x LTS versions as that's what we are using and can't see anything in Mathlive that would require the latest version of Node. 
We were maintaining an entire fork just for this change but it makes it much harder for us to take updates, so it'd be great if the main package could reduce the required Node version a little bit.

Reducing node required version to LTS

---

examples/speech/index.html
examples/speech/index.js
examples/vue/index.html
src/addons/outputSpokenText.js
src/editor/editor-mathfield.js
src/editor/editor-shortcuts.js
src/mathlive.js
tutorials/SELECTORS.md
tutorials/USAGE_GUIDE.md

As per a conversation with Arno, added an option to $text and $selectedText so that one can see the markup when SSML is generated with text highlighting turned on ("read aloud" functionality).

Spoken ssml with highlighting

---

src/editor/editor-editableMathlist.js

This fixes an error I got when pasting `\frac{n\cdot \left(n+1\right)}{2}` into a mathfield with `removeExtraneousParentheses` active by default.

Fix incorrect loop-condition

---

package.json

Since the type-declaration-file has not the same name as the emitted js-file, Typescript is not automatically associating them with each other.

Add types-info to package

---

src/mathlive.js

I think it would be nice to have a way to close the loop on MASTON manipulations. This allows an end user to take the generated AST, manipulate it, and output some other new generated latex within the mathfield.

Expose a method to convert the AST back to latex

---

css/mathlive.core.less
src/editor/editor-mathfield.js
src/editor/editor-popover.js

relevant to #229 .
Fixed the bug that wrong popover y position when user scroll down.
Set popover position relative to browser's screen size.  When current height of popover is not sufficient to render bottom, render it above the caret position. 
Prevent appearing popover out of screen. Also considered with virtual keyboard size to prevent appearing below the virtual keyboard.

fix Popover position

---

css/mathlive.less

Hi, I needed to change the font folder to create a plugin for the discourse.org forum software. the @font-folder variable was hard coded in one place. Maybe this is of help to others in a similar situation.
Thaaaanks 
spirobel

make all links to fonts depend on the @font-folder variable

---

src/editor/mathfield-pointer-input.ts

(and maybe others?)
Test plan:
- Visit /examples/basic/index.esm.html on an iPhone 6
- Tap into mathfield; it gets focus
- Tap around mathfield to move cursor

Fix focus bug on iOS 12 and Firefox/Android

---

package.json

After moving typescript definitions to public folder, typescript was unable to find type definitions. This fixes that.
@arnog If we had an e2e test for this, it would've been detected earlier.
Thanks for your efforts 👍

Fix broken typescript definitions path

---

css/mathfield.less
package-lock.json
src/editor/mathfield-class.ts
src/editor/virtual-keyboard-utils.ts

Changing `data-tooltip` to `data-ML__tooltip` better scopes the built-in
tooltip styles, preventing collisions with other elements/components.
Fixes #519

Change `data-` selector for tooltip styles

---

src/core/definitions-enclose.ts

Previously, the first argument could be an empty array `[]`. Actually, maybe that's a bug with the argument parsing function?

fix: Don't throw an error when the first argument of \enclose is empty

---

src/editor/model-selection.ts
src/editor/model-utils.ts
src/public/config.ts

Fixes #591
However, this doesn't add wrapping around for `upward`s and `downward`s movement.

fix: Add more ways to move out of mathfield #591

---

src/editor/shortcuts-definitions.ts

Previously, typing "sqrt2" would insert "\sqrt[]{}2". With this change, typing "sqrt2" will insert "\sqrt[]{2}".

Fix issue when typing "sqrt"

---

src/public/mathfield.ts

This improves the public `getConfig()` type for the single key case. 
e.g. `mathfield.value.getConfig("keybindings")` will now return a `Keybinding[]`.
@ arnog 
If you want, I can also change the internal `getConfig` methods to use these typings. Also, if it would be useful, I can try to create a fully typesafe version of `getConfig(keys: string[]): MathfieldConfig;` Regarding the types, why does the last overload exist? Furthermore, why is `getConfig` the only method that doesn't have a `$`?
Furthermore, while I'm at it, if there are any other bits and bobs that could use some extra type safety, I'd be more than happy to take a look at them!

Improve getConfig typings

---

src/editor/commands.ts
src/editor/keybindings.ts
src/editor/mathfield-class.ts
src/editor/mathfield-keyboard-input.ts
src/public/config.ts
src/public/mathfield.ts

This PR slightly improves some types.
I chose to use `[SelectorPrivate, ...any[]]` for now, because the August 2020 version of Visual Studio Code, which comes with Typescript 4.0, hasn't been released yet. (The expected release date is September 9)
By the way, are such minor improvements to the types `fix`es or `feat`ures?

Improve getConfig and selector types

---

src/editor/keybindings-definitions.ts
src/editor/mathfield-class.ts
src/editor/mathfield-utils.ts
src/public/mathfield.ts

I added public `getCaretPosition()` and `setCaretPosition()` methods. This fixes #101 
However, I do have some open questions that I'd like to address:
**getCaretPosition**
- It can return `null`. Is that fine? Or should it return `undefined`? 
**setCaretPosition**:
- Should it call `model.announce('move', ...)`?
- Should it focus the mathfield when calling it?
- Is the boolean return value fine or should it pick the nearest point when it is out of bounds?

Added getCaretPosition() and setCaretPosition()

---

src/editor/commands.ts
src/editor/mathfield-keyboard-input.ts

Fixes #198 
This is a rather simplistic way of checking if backspace was pressed and then handling it.
It doesn't really handle the case where you type `su` on the normal keyboard, then hit `[Backspace]` on the virtual keyboard and then type `m` on the normal keyboard. In fact, a number of cases where the normal and virtual keyboard are mixed don't work as expected. Furthermore, the virtual keyboard doesn't ever modify the keystroke buffer, is that intentional?
Also, I noticed that mathlive doesn't handle `su` `Ctrl+V` `m` correctly either.

fix: Handle backspace with regards to inline shortcuts

---

src/core/definitions-utils.ts
src/core/delimiters.ts
src/core/modes-text.ts
src/core/tokenizer.ts

Fixes #599 
(arnog, thank you very much for the guidance)
There are 3 further functions where `TEXT_SYMBOLS` is being used. I'm not sure if I should add anything to them.
- `commandAllowed`: It isn't being called anywhere
- `getValue`: It is only being called with 'math'
- `emit`: What is this function used for?

Fix non canonical text characters

---

src/editor/parse-math-string.ts

in math editor writing a `sqrt` string is translated to a
`\\sqrt{\\placeholder{}}` expression. Pasting the same `sqrt` string
into the editor is translated into a `\\sqrt{}` expression.
This happens because `parseMathExpression` does not provide
a fallback value when sqrt / sqrt[3] values are empty

editor/parse-math-string: pasting/writing `sqrt` should behave the same

---

src/core/definitions-extensible-symbols.ts

fix: Don't use skipBoundary with xrightarrow and others

---

css/virtual-keyboard.less
scripts/build.sh
src/editor/virtual-keyboard-commands.ts

Hopefully, I got your idea right in the discussion of the issue.
So here I've made a property evaluation for alternate keys based on variables, during the test no issues were found. Anyway if you have any concerns or suggestions to make it in another way, feel free to let me know.

Fix issue #727: The alternate keys panel renders the wrong layout for the "logic" (∀) key

---

src/addons/math-ml.ts

Hi,
I've noticed that there is a typo on the ApplyFunction hexadecimal symbol value so I decided to fix it. Not sure that it is related to the [issue #737](https://github.com/arnog/mathlive/issues/737) but seems that this fix makes the converter logic work a bit better (according to the console logging messages). If you have any suggestions please let me know and I'll try to apply them.

fix the typo of ApplyFunction hexadecimal value

---

tutorials/CONTRIBUTOR_GUIDE.md

Removed extra https:// from URL

Fix URL typo of jsben.ch

---

examples/basic/index.esm.html
src/addons/math-ml.ts

Currently when forllowing latex text are used `\int_0^x` it produce the wrong output. This output dont have information about sup and sub for integral.

Fix support for sup & sub for mathml output

---

src/addons/definitions-metadata.ts
src/core-atoms/group.ts
src/core-definitions/styling.ts
src/core/parser.ts
src/core/span.ts

It basically mimics what was done for cssId, to add a command.   Addresses #785 
fields added have a form udata-* to avoid conflict with data- fields that mathlive already adds.

add Data command to add data properties to dom elements

---

tutorials/USAGE_GUIDE.md

Currently the code snippet is invalid, since the mandetory `display` key is not included. I would argue that is is a good idea to have only working code in the documentation.

Add display = [] to example code to make code snippet valid

---

src/editor-mathfield/mathfield-private.ts

Here is what the spaces look like in css inspector. This issue is causing problems with allowing for a `ML__fieldcontainer` to have `display: inline`.
https://imgur.com/WB5K6w6

Remove whitespaces within mathfield span

---

src/editor-mathfield/mathfield-private.ts

Using setOptions on a mathfield, the virtualKeyboard field was not reinitialized with the new options.

Fix #833 : custom virtual keyboard not displaying

---

src/editor/options.ts
src/editor/virtual-keyboard-commands.ts
src/public/options.ts

I added a new option, `virtualKeyboardAppendTarget`, that enables customization of where in the DOM the virtual keyboard gets inserted. 
The use case for this is having a working keyboard when [full screening DOM elements](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) that contain MathLive, eg.
```html
// ...
<div id='container'>
<div id='math-field'></div>
</div>
<button id='toggle-fullscreen'>Toggle fullscreen</button>
<script type='module'>
import MathLive from 'mathlive'
const container = document.getElementById('container')
document.getElementById('toggle-fullscreen')
.addEventListener('click', () => container.requestFullscreen())
const mathField = document.getElementById('math-field')  
MathLive.makeMathField(mathField, {
virtualKeyboardMode: 'onfocus', …
```

Allow appending the virtual keyboard to an arbitrary element

---

src/core-atoms/group.ts

When typing `\htmlData{test:test}{x=0}` in mathfield than adding something else - tex code looses brackets in second part of command. For example ` \htmlData{test:test}{x=0}` => `\htmlData{test:test}x=0somethingelse`. `\class`, `\cssId` has the same behaviour.
`\htmlData{test:test}{x=0}` => `\htmlData{test:test}{x=0somethingelse}`

Fix loosing brackets in mathfield for htmlData class cssId tex commands

---

src/editor/l10n-strings.ts

removing new line with spaces in order to fix
a minor linting warning after install

src / editor / l10n-strings: fix linting warning

---

package.json

add to dev dependencies @typescript-eslint/parser package.
This fixes the following error during install:
[!] (plugin eslint) Error: Failed to load parser
'@typescript-eslint/parser' declared in '.eslintrc.json':
Cannot find module '@typescript-eslint/parser'
Require stack:
- /home/web/mathlive/.eslintrc.json

package: add @typescript-eslint/parser

---

src/common/capabilities.ts
src/editor/keybindings.ts
src/editor/l10n.ts
src/editor/options.ts
src/editor/speech-read-aloud.ts
src/public/mathfield-element.ts

Seems like the optional chaining operator wasn't enough to guard against `ReferenceError` on the server. This PR will add guards wherever `navigator` may be unsafely accessed.
Will also do the same for `window`.

fix: navigator access on the server

---

src/public/mathfield-element.ts

Stumbled upon this typo while debugging virtual keyboards in my project. Pretty sure there should be no boars involved 😅 🐗

fix: typo in virtual keyboards MF property

---

src/editor/virtual-keyboard-utils.ts

fix broken import on virtual-keyboard-utils
throwing an error on install

virtual-keyboard-utils: fix broken import

---

package.json
scripts/start.js

serve-http has an issue with a node >= 14 fs.watch breaking
change on linux causing the server to crash.
on efea7a7a0080870712cdc81a394435b4953e38d1, while introducing
estrella, serve-http was dismissed in favor of http-serve.
In order to be able to run a server on linux machines,
let's re-introduce http-server
rif. https://github.com/rsms/serve-http/issues/6

start: use serve-http instead of http-serve to fix node 14 bug w/ linux

---

src/public/mathfield-element.ts

The `soundsDirectory` option wasn't an attribute in the `optionsAttributes` array, meaning it wouldn't work if you set it from an attribute.
This is needed because MathLive tries to load the fonts and sounds immediately from the constructor. If it fails, it sends a bunch of errors to the console. In order to prevent this first set of errors, you'd need to pass these directories into the constructor:
```javascript
const mfe = new MathfieldElement({soundsDirectory: ..., fontsDirectory: ...})
```
However, we're not using this constructor -- we're using a Virtual DOM setup (in Elm) that directly adds a custom element to the DOM through `document.createElement`. Thus, our only option to suppress the first set of errors is to set the directories as an attribute.

Add sounds-directory to list of valid attributes

---

src/editor-mathfield/mathfield-private.ts
src/editor-mathfield/mode-editor-math.ts

- Always add `ML__placeholdercontainer` because it could be set as readonly through `setOptions` 
- when attaching nested mathfields, request update only when the position or font has changed significantly.
- remove nested mathfields when setting the expression through `setValue` and the placeholderId is not in the new expression.

Fix fill in blank issues.

---

src/editor-mathfield/mathfield-private.ts
src/editor/commands.ts
src/editor/virtual-keyboard-utils.ts
src/public/mathfield.ts

Hello 👋 I was able to tackle part of the problem discussed in #1087.
This change enables the field to scroll after input for command that are using the `performWithFeedback` method, with the same behavior as keybindings and typedText.
This alone will allow to move the caret in the math-field using the left/right buttons in the virtual keyboard with the same experience as using the arrow keys on the physical keyboard.
I'm still figuring out how to extend this fix to buttons that use the `insert` method.
Any help in this direction would be wonderful!

Fix #1087 - math-field scrolling on input inconsistent behavior

---

src/editor-model/commands-move.ts

This PR fixes [two small issues](https://user-images.githubusercontent.com/446007/139747586-5794027c-dd05-4a0c-a253-85fd0223cab8.mp4):
1. When tabbing out of an empty field, very often nothing happens. You may have to jam on the button a lot to get it to work.
- This was fixed by detecting the "root" atom more accurately. I'm not 100% confident in this fix, but `treeDepth` as currently implement was never going to be less than 1. When the field is empty, the atom you get has a `treeDepth` of 2.
2. When shift-tabbing out with the cursor at the beginning of a field, it takes two inputs to shift-tab out.
- This was fixed by clamping the index passed to `getAllAtoms`; when at the beginning of a field, we would pass `-1`, which would cause us to return `undefined` as an atom.

Fix tabbing out of empty fields and the beginning of fields

---

src/addons/definitions-metadata.ts
src/core-atoms/group.ts
src/core-definitions/styling.ts
src/core/box.ts
src/core/mathfield-box.ts

HTML styling is supported in Katex and I think this will be a good idea to be supported here too. [Refrence](https://katex.org/docs/supported.html#html).
I made the necessary changes and tested them.
Thanks.

added commnad "\HTMLStyle" to support html styling

---

src/public/mathfield-element.ts

Before, changes to the `readonly` attribute were observed but changes to `read-only` were not. This was causing wrong behaviors when adding `read-only` to a `math-field` element, for example it was allowing users to modify the content of a `math-field` after adding the `read-only` attribute programmatically.
You can see here the behavior of a `math-field` after toggling `read-only` or `readonly`:
https://codepen.io/LuisMesa/pen/GROgOZz?editors=1010
https://user-images.githubusercontent.com/14155607/151276682-6043e35e-c2ef-4f88-a975-c75746211bec.mov
This is a related issue I just created: https://github.com/arnog/mathlive/issues/1319
This PR will prevent users from typing in the `math-field` after `read-only` was added.

fix: properly observe changes to the `read-only` attribute

---

src/core-atoms/group.ts
src/core-definitions/definitions-utils.ts
src/core-definitions/styling.ts

fix `\ne` `\neq` disappearing operator bug documented in issue #1024
`\ne` and `\neq` operators' `createAtom` function is returning a `GroupAtom` class instance with an empty command value.
This causes `Parser`'s `parseCommand` method to populate `verbatimLatex` value with an empty string.
The empty `verbatimLatex` value causes a malfunction in `Atom`'s static `serialize` method removing `\neq` and `\ne` operators from displayed latex.

core-definitions: fix \ne \neq rendering issue

---

css/virtual-keyboard.less

Fixed: prevent virtual keyboard from closing when clicking on other parts of the kb other than the key elements

---

CONTRIBUTING.md

Direct the `Contributor Guide` link to the correct file path.

fix: link to Contributor Guide

---

src/editor-mathfield/pointer-input.ts

closes #1366
Also prevent throw if `PointerEvent` is not supported / doesn't exist in a browser.

fix: Fixed #1366 by removing stop propagation 

---

src/core-definitions/environments.ts

Before:
After:
LaTeX: `\begin{aligned}x^2 & =12 \\ x & =\sqrt{12}\end{aligned}`

fix: add appropriate gap to aligned environment

---

src/editor/shortcuts.ts

I think this is an appropriate fix for these issues. I don't think it breaks anything else.
- `sin` -> `sinh` still works
- `xx` followed by 1 more `x` displays `×x` instead of `x×`
- all combinations of `>` and `=` and backspacing act as expected
Let me know if I missed anything.
closes #726
closes #759
closes #1362

fix: Fixed #1362 and #726

---

src/editor-mathfield/mathfield-private.ts
src/editor-mathfield/mode-editor-math.ts

I submitted PR for the first time. I'm very sorry for some problems in the format.
I use mathlive in my project. I defined a macro `OR`. When I execute the code `mf.executeCommand(['insert', '\\OR'])`, I find that mathlive can't render this macro accurately. When I execute code `mf.setValue('\\OR')`, the same result occurred. I read mathlive and found some problems, then fixed them. The following is my test code, which comes from `examples/basic/index.html`
```html
<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="utf-8" />
<title>MathLive Basic Example</title>
<style>
body {
color: #444;
background-color: #f9f9f9;
}
main {
max-width: 820px;
margin: auto;
}
math-field {
border: 1px solid #ddd;
padding: 5px;
margin: 10px 0 10px 0;
border-radius: 5px;
background-color: #fff;
} …
```

fix: custom macro do not work when executeCommand insert or MathfieldElement setValue

---

src/core/delimiters.ts
src/editor-mathfield/mode-editor-math.ts

This fixes #1415 and keeps the contents of parentheses together when you press the division key.
Behavior in a few cases can be seen here:
https://user-images.githubusercontent.com/446007/162076602-12b883c3-6093-4d42-95b0-9adae3c92b5d.mp4
When calculating what the "implicit argument" to division is, we follow this algorithm:
1. Consume atoms until you hit some sort of binary operator OR until you hit a closing delimiter.
2. If you hit a closing delimiter, consume atoms until that delimiter has been closed.
We keep track of which delimiters we've seen so far so that nested delimiters work correctly.
If the closing delimiter is not matched up, we consider the entire preceding expression part of the implicit argument. There may be better behavior here -- thoughts, @arnog?
We look for exact …

Group atoms inside of parentheses as implicit args (#1415)

---

src/addons/auto-render.ts

fix typo in code
static math expressions not rendering inline (textstyle) when latex code is wrapped inside `<script type='math/tex; mode=text'>` . The issue is the result of a minor typo in code which this Pull Request aims to fix

fix: typo in auto-render.ts

---

src/editor/virtual-keyboard-commands.ts
src/editor/virtual-keyboard-utils.ts
src/public/commands.ts

Currently if options are set on a visible keyboard it is implicitly removed from the DOM and not re-shown.
This change instead rebuilds the keyboard to reflect the new options if it is visible.

Allow options changes to visible virtual keyboards

---

src/editor-mathfield/mathfield-private.ts
src/editor/virtual-keyboard-commands.ts
src/editor/virtual-keyboard-utils.ts

The implementation of `disable` was implicitly removing the element altogether. This PR breaks out the destruction of the virtual keyboard element into the hiding itself.
This implicit hiding meant that a `disable` had been removed from `onBlur`, resulting in multiple fields receiving keyboard events. By decoupling the disabling from the hiding, we can now avoid that problem whilst still allowing the `off` keyboard mode to provide a persistent keyboard.

Disable the keyboard when a field is blurred

---

src/core/fonts.ts

`isBrowser() && !/firefox|safari/i.test(navigator.userAgent);`
The above test for browser in `supportLocalFontEnumeration` method is failing as Chrome and Microsoft Edge also has the word "Safari" in navigator.userAgent
The failed condition forcing the fonts to load multiple times in all major browsers, and resulting in static math to flicker each time mathfield is focused and virtual keypad is toggled to `showVirtualKeyboard`
This Pull Request aims to add alternate approach to detect loaded fonts in browser, and is tested to be working on latest versions of Chrome, Firefox, Safari and Microsoft Edge

prevent fonts loading multiple times

---

src/editor/virtual-keyboard-commands.ts

and fix https://github.com/arnog/mathlive/issues/1523
I added a check for the container padding modification in `showVirtualKeyborad`
https://github.com/arnog/mathlive/pull/1524/files#diff-4326e5672802bba8b043a8c8d6ce9ff0c70475dae04afc6072502c21e765dbccR202-R211
I don't know if we should execute the rest of the code in case when the keyboard is already visible, so I preserve the current funcionality

rewrite toggleVirtualKeyboard in terms of show/hide VirtualKeyboard 

---

src/editor-mathfield/pointer-input.ts

See issue for problem description. The problem is that nearestAtomFromPointRecursive initializes the result incorrectly, and children are not considered as closer candidates if the group is a "root". The fix is to broaden the criterion for special initialization from "group" only to "group" or "root".

fix for issue 1605

---

src/public/mathfield-element.ts

Before, an input that was just transformed into a readonly input could have its keyboard open if `virtualKeyboardMode` is `off`. Also, any attempt to close it using the `hideVirtualKeyboard` command would be ignored because this [check](https://github.com/arnog/mathlive/blob/507c7d833c3abdb4f83786735b357e4b47d02d1c/src/editor-mathfield/mathfield-private.ts#L633) related to `readonly` would prevent it. To fix this, we should close the keyboard if the input becomes a readonly input and if it was open.
You can see the faulty behavior in [this](https://codepen.io/LuisMesa/pen/WNJNXVB) Codepen.
Below you can see how the keyboard remains open:
https://user-images.githubusercontent.com/14155607/188730446-51237bd2-c381-4c8d-b00c-3e52bc07ef67.mov

fix: hide keyboard if `readonly` is added while `virtualKeyboardMode` is `off`

---

.vscode/settings.json
src/core/atom-class.ts
src/editor-mathfield/mathfield-private.ts
src/editor-mathfield/utils.ts
src/editor-model/commands.ts
src/editor-model/model-private.ts

I made it measure pixels and compare to the (base) elements of the upper or lower matrix cell. The way I get the DOM elements feels hacky.
LaTeX I used to test:
```
\begin{align}b+c+d+e & =f \\ a+\sqrt{a^2+b^2}+b & =g\end{align}
```
You can go from in the middle of the sqrt to the same (closest) position above. It doesn't work in reverse - not sure if that is desired?
Also this logic could probably be applied to moving between fraction upper and lower, but I haven't spent the time to look for where the code is for that.
I also made sure it works when the element is rotated by CSS.

Better vertical navigation

---

src/core-atoms/array.ts
src/editor-model/array.ts
src/editor-model/commands.ts
src/editor-model/model-private.ts
src/editor/keybindings-definitions.ts
src/public/commands.ts

LaTeX to test:
```
\begin{bmatrix}a & b & c \\ d & e & f \\ g & h & i\end{bmatrix}
```
new hotkeys:
| Key Binding                                                         | Command           |
| :------------------------------------------------- | :----------------- |
| <kbd>ctrl/⌘</kbd>+<kbd>[Backspace]</kbd> | `removeRow`       |
| <kbd>shift</kbd>+<kbd>[Backspace]</kbd>   | `removeColumn`  |

feat: add matrix remove row/column keyboard shortcuts

---

src/core-atoms/array.ts
src/core-definitions/environments.ts
src/editor-model/array.ts

Made it so when you type in `\begin{some environment}` you get placeholders instead of empty brackets or empty space which lets you better know where you are inserting.
Also limited the columns when adding/removing using hotkeys based on `minColumns` and number of `align` elements in `colFormat`.

feat: give empty environments placeholders, limit environment columns

---

src/core-atoms/array.ts
src/editor-mathfield/mode-editor-math.ts
src/editor-model/array.ts

There is a preexisting bug where if you highlight the entire innards of the environment and paste it will paste outside - I'm not sure how to address this...
https://user-images.githubusercontent.com/12475567/196035430-52cc342b-7298-4939-b95f-994c21faf064.mp4
Also not sure how to handle multiple rows... at least it's a start.
Also fixed an issue when copying from multiple columns to outside an environment - it included the `first` elements which makes things weird when they aren't in the first position.

feat: allow pasting of multiple columns in environments

---

src/public/mathfield-element.ts

The `attributes` section of these docs https://cortexjs.io/docs/mathlive/#(MathfieldElement%3Aclass) is missing a `virtual` prefix for valid keyboard options.

Fix virtual keyboard options in docs

---

css/virtual-keyboard.less

The entire keyboard had `cursor: pointer` when it should just be the buttons you can click.

fix: use cursor pointer on just the buttons of the virtual keyboard

---

src/editor/virtual-keyboard-commands.ts

Closes #1783 
I couldn't find any references to `lower-command`, `upper-command`, `symbols-command` in the repo, and `complete` already gets executed in `mathfield-private.ts:1172`, so I'm not sure if this code is needed and it fixes the issue.
The issue being that because it's a remote keyboard anything going through `executeCommand` is delayed by 1 frame because it's handled by event listeners? So it was completing the inserted `\` one frame later.

fix: remove extra complete call

---

src/editor/atom-to-speakable-text.ts
test/smoke/index.html

This PR adds support for convert matrices in latex to speakable text. It also adds a new output in the Mathlive Smoke test page to test this feature.

Add matrix support for latex to speakable text

---

src/editor-mathfield/mathfield-private.ts
src/editor/keyboard.ts

trivial addition of inputtype="none" on textarea seems to successfully disable OS virtual keyboard, but otherwise stay functional.

fix for ctrl x/c/v

---

src/editor-mathfield/mathfield-private.ts

Since prompt body is a branch, the offsets behave unexpectedly, souse `getBranchRange` instead.

#1884 again

---

src/editor-mathfield/mathfield-private.ts
src/public/mathfield-element.ts

Currently `setPromptContent` fires a `change` event, but I am calling `setPromptContent` on `change` (to strip answers from latex sent to a student).

Allow insertOptions in setPromptContent

---

src/editor/keyboard.ts

Adjusted the logic of when keyboardSink selection buffer is cleared. It is now cleared on keydown for any input that changes the buffer (fixes Firefox issue where it wasn't possible to replace a selection for a key press that wasn't a shortcut).
Buffer is no longer automatically cleared for non content changing commands so that Cmd-A and Shift-Arrow work to select on Safari. Arrow keys alone still work to clear selection buffer since this is handled by the current selection update logic.

fix: Firefox and Safari selection issues, fixes #1898

---

src/core-atoms/prompt.ts
src/editor-mathfield/commands.ts
src/editor-mathfield/mathfield-private.ts
src/public/commands.ts

`insertPrompt` command inserts a prompt with random 6 char id or given `id`.
Prompts with no content were too small, so I widened them to `3 * fboxsep` (previously 2)

insertPrompt command and widen empty prompt, allow latex mode in prompt

---

src/editor-mathfield/mode-editor-math.ts
test/playwright-test-page/index.html
test/playwright-tests/smart-fence.spec.ts

Fixes #1656 and #1742 (#1742 is a duplicate of #1656). This pull request also fixes a regression of #1691 (the #1691 regression occurred since 0.91.2, I didn't determine exactly which commit introduced the regression). 
Additionally, fixes issue where deleting left delimiter and retyping left delimiter did not trigger an input event.
End-to-end tests have been added for these fixes and the previous delimiter issues (#1691, #1375,  and #1845) to make sure regressions were not introduced with these changes and to make sure any regressions on these issues will be detected in the future.

Delimiter editing fixes

---

src/editor-mathfield/mathfield-private.ts

Previously, math-field elements would steal focus from other focused element types when switching tabs. This caused quite a bit of issues with my app since it has many math-field and text input elements on the same page and switching tabs would cause a math-field element to always gain focus, even if a text input was previously focused, making it seem like a random element is being selected. This commit fixes this issue while still making sure #1545 remains fixed (math-field elements will still keep focus when changing tabs, just like textarea elements). 
The window blur event gets triggered even when not leaving a tab (focus switching between elements on the page). By checking that `event.relatedTarget` is null before adding the focusing callback, the callback is only added when the tab …

fix: switching tabs focus fix

---

src/virtual-keyboard/commands.ts
test/playwright-tests/virtual-keyboard.spec.ts

#1357 
This seems a regression after 0.90.
Test case provides the new way to switch keyboard layer by shift.

fix: switchKeyboardLayer

---

test/playwright-tests/physical-keyboard.spec.ts
test/playwright-tests/virtual-keyboard.spec.ts

Adds regression tests for #1975, #1978, and #1981
Also skips webkit iframe test in CI only since this test fails most of the time in CI even though it passes locally. This iframe test is same origin, which is why it didn't catch #1982. The current iframe test is testing the virtual keyboard, so it needs to be same origin. #1982 uses the physical keyboard instead, I'll attempt to create a test for cross-origin physical keyboard once there's a fix for #1982.

Add regression tests

---

scripts/start.js
test/playwright-test-page/iframe_test.html
test/playwright-test-page/index.html
test/playwright-tests/physical-keyboard.spec.ts
test/playwright-tests/virtual-keyboard.spec.ts

Move iframe tests to their own page to prevent nested iframes. The same-origin iframe test uses the virtual keyboard and the cross-origin iframe test uses the phyiscal keybard

tests: add cross-origin Iframe test (#1982)

---

css/mathfield.less

As mentioned in the gitter chat, this addresses selection highlighting showing for unfocused math-field elements after changes for 0.94.5

fix: selection highlight only for focused math-field

---

src/addons/math-ml.ts

In 'convertLatexToMathMl(...)' added closing angle bracket to '\<mo>' when left delim added

fix: added closing angle bracket in LaTeX to MathML conversion

---

css/mathfield.less

Fixes typo in css variable name

fix: typo in contains-highlight-background-color css variable

---

css/virtual-keyboard.less

The keyboard does not display properly on browsers which do not support `cqw` as it is a relatively new feature. A friend had Chromium 103 installed when the minimum is 105 for this feature.
The good news is in the majority of places it is used for setting the width to a percentage width of the containing element, which `%` replaces seamlessly.
There still remains a 4cqw inside of `--_keycap-font-size` which can not be simply replaced with % because that scales relative to font size. On browsers which do not support `cqw` it will default to inherit.
closes  #2028

Virtual Keyboard display on older browsers

---

src/virtual-keyboard/utils.ts

The current long press delay for keys is 200ms which is quite short, this PR increases it to 300ms for improved accessibility.

increase long press & hold delay for key variants

---

src/editor-mathfield/keyboard-input.ts
src/virtual-keyboard/utils.ts
src/virtual-keyboard/virtual-keyboard.ts

Fixes https://github.com/arnog/mathlive/issues/2064
Fixes https://github.com/arnog/mathlive/issues/2065
FYI @zeyad-ahmad-aql, this changes part of your previous pull request https://github.com/arnog/mathlive/pull/1961
Would you like a config option so that physical keyboards still have a toggling `Shift`?

feat: Press/hold `Shift` modifier instead of toggle when using with physical keyboard, and fix rapid toggling of `Shift` on Windows

---

css/virtual-keyboard.less

I think it's a typo because the first occurrence is correct:
https://github.com/arnog/mathlive/blob/6175225fe2a26b7f1a4da5b1daec245045bf293d/css/virtual-keyboard.less#L62-L63
This simple fix will enable configuring the hover background color of keycaps.

fix: virtual-keyboard keycap hover color variable

---

css/virtual-keyboard.less

Fixed a typo that causes the keyboard to adapt to system theme even when `theme="dark"` is set.

fix: remove duplicate virtual keyboard selector in dark mode

---

package.json

Adds an export to be able to reference the Vue file.

Add Vue export (#2145)

---

src/common/capabilities.ts

I think an improvement is that when `mathVirtualKeyboardPolicy` is 'auto', the virtual keyboard should only be shown (by default) if the user's device's _primary_ pointer is touch, not just if touchscreen is supported. 
My personal use case is as follows. I have a touchscreen laptop with two modes of input, keyboard and touchscreen. In normal use, I only use the regular keyboard, and the virtual keyboard is not useful. In this case, `window.matchMedia("(pointer: coarse)").matches == false`. Although I am _able_ to use the touchscreen when upright, in most cases I don't. Instead, when I wish to use the touchscreen, I physically fold the laptop. This causes an OS level change that disables the keyboard and also causes chrome to say `window.matchMedia("(pointer: coarse)").matches == true`. …

Only consider as touchCapable if primary pointer is touch

---

src/virtual-keyboard/virtual-keyboard.ts

handleMessage method in virtual-keyboard.ts ends up in infinite recursion. 
`"window === window.parent"` (current master) check prevents recursion for standard window but fails for iframe. 
`"window !== window.parent"` (previously) check prevents recursion in an iframe but fails for standard window.
if statement should only check `commandTarget !== 'virtual-keyboard'` and return if true. 
This way it prevents recursion for both, standard window and iframe.
I tested this on an extension for third party app.
Thanks for the great library!

fix: Stack overflow in sandboxed mode when in an iframe from different origin

---

src/editor-mathfield/autocomplete.ts

By default, when inputting LaTeX commands, accepting suggestion is done by `[Tab]` (`accept-suggestion`), and exiting to math mode is done by `[Enter]` (`accept`).
This PR adds a `accpet-all` option to autocomplete, which does both `accept-suggestion` and `accept`. If there are no suggestions, only `accept` is done. This allows users to bind keys to accept suggestion and exit latex mode at the same time, which is convenient. (which is also consistent with LyX if you know it)

feat: accept-all option for autocomplete

---

README.md

People are confused about installing and using this library with npm and plain javascript. I was especially confused about the initialization part.
Adding this information to the main README helps out people who visit the npm registry and want to get started quickly without diving deep into the documentation.

Add npm installation instructions to README

---

src/virtual-keyboard/virtual-keyboard.ts

In commit 645fa9d66b8a63 for #1914, the math virtual keyboard was prevented from disappearing when a math-field with mathVirtualKeyboardPolicy = "manual" loses focus.  However, if subsequently something else loses focus that isn't a math-field, the virtual keyboard disappears anyway.  The attached patch avoids that problem.
Thanks for this amazing library!

Only pay attention to focusout of math-elements

---

src/formats/atom-to-math-ml.ts
src/latex-commands/definitions-utils.ts

1. Expected output for `\text{A\_2}` is `A_2`. Current mathlive version produces output `A\_2`.
_ is a special character in TeX and for getting character '_' one should use `\_`
2. \text{A}_2 produces incorrect mathml. current mathml output is
```
<mrow><mtext >A</mtext><msub><mn>2</mn></msub></mrow>
``` 
Expected output is
```
<msub><mtext >A</mtext><mn>2</mn></msub>
```
This pull request adds `'\\_': 0x005f` to `TEXT_SYMBOLS` in  src/latex-commands/definitions-utils.ts to fix 1.
function `scanTeX` modified in src/formats/atom-to-math-ml.ts to take care of superscript and subscripts with `\text`

Fix: 1. For \_ in \text command to produce expected output. 2. For Generting correct when \text used with superscript/subscript 

---

src/core/v-box.ts
src/formats/atom-to-math-ml.ts

When array environment with `@{}` in column specifier as below the browser sometimes hangs and content always disappear or does not update in WYSIWYG editor
```
\left\{
\begin{array}{@{}l@{}}
A + B\\
C + D
\end{array}
\right\}
```  
`@{}` is commonly used in array to remove space before/after a column. If above LaTeX code is used in the mathlive demo page
Following error appears in console
```
Uncaught TypeError: Cannot read properties of undefined (reading 'shift')
at Qp (mathlive.min.mjs:192:15305)
at eh (mathlive.min.mjs:192:15993)
at new U (mathlive.min.mjs:192:17147)
at Dh (mathlive.min.mjs:2803:18674)
at t.render (mathlive.min.mjs:2803:14292)
at nh (mathlive.min.mjs:192:42110)
at t.createBox (mathlive.min.mjs:192:29931)
at t.render (mathlive.min.mjs:2803:23269)
at nh …
```

Fix: When LaTeX array environment is used with @{} in column specifiers browser hangs.

---

css/mathfield.less

Removing the `isolation: isolate` css property allows the context menu to layer above other mathfield components that appear later in the DOM. This change prevents multiple mathfields from having a context menu open at the same time. The isolation setting was preventing the click handler div below the context menu from handling clicks over other mathfield components (or over other clickable elements) that appeared later than the mathfield in the DOM. Because of this, clicking on other mathfields or buttons did not close the context menu and two cursors would also appear leading to confusing behavior. This was also leading to rendering issues on Firefox which can be seen in the first screen recording below. The rendering issues only appeared on Firefox. However, the multiple context menus …

fix: keep context menu above other mathfield components

---

test/playwright-tests/physical-keyboard.spec.ts

Many thanks for the fixes for #2291, #2293, and #2294. The tests for my app are now passing. I'm looking forward to rolling out the new context menu feature!
This pull request adds a Playwright regression test that covers #2291, #2293, and #2294.

tests: add regression test that covers #2291, #2293, #2294

---

css/mathfield.less

Appears to be a regression of #1861, restores the original fix from [5b3999b](https://github.com/arnog/mathlive/commit/5b3999bca74eb2ac55edeaa977a7edd1ecb8b48e). The main side effect of this fix is that mathfield elements cannot be selected by clicking directly on the border but it fixes the bug in Firefox where clicking multiple times on the border leads to a focused mathfield that cannot be edited until focus is lost and regained (also fixes the multiple cursor issue on firefox that can occur with the same sequence of events).
Another benefit of this fix is that the default browser context menu for a text area, instead of the expected MathLive custom context menu, no longer appears when right clicking on the border of the mathfield (observed on Firefox and Chrome, not tested on Safari).

fix: fixes regression of firefox border selection bug

---

src/ui/menu/menu-item.ts

When using touch input with the context menu, all of the previously clicked context menu items remain highlighted when the context menu is reopened (see first screen recording below, tested on Chrome and Edge). This change ensures that the most recently clicked item will be returned to the non-active state after the event fires. I think the root cause of the issue is that the `pointerenter` and `pointerleave`  don't both fire for touch input so the accounting of `activeMenuItem` is not working the same way as it does for mouse events. I tried setting `touch-action: none` on the menu items as a alternative solution, but that did not work.
Screen Recording of Previous Behavior:
[before_context_menu_fix.webm](https://github.com/arnog/mathlive/assets/6439649/e4471c16-7d7f-43a8-a9b7-f9cc35e3caf …

fix: prevent context menu highlight from persisting for touch input

---

src/ui/events/utils.ts

The desktop versions of Safari and Firefox do not define the `TouchEvent` constructor (see the [TouchEvent MDN page](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent#browser_compatibility) for details). Currently, two of the functions in `utils.ts` use `TouchEvent`, which leads to an unhandled `ReferenceError: Can't find variable: TouchEvent` in certain situations. In particular, I was noticing this issue when using arrows to navigate MathLive's context menu on desktop Safari leading to the arrow keys not doing anything with the context menu. This fix checks for the existence of `TouchEvent` before using it and fixes the arrow key navigation of MathLive's context menu on desktop Safari and Firefox.

fix: test for the existence of TouchEvent before using

---

src/editor-mathfield/commands.ts
src/editor-mathfield/mathfield-private.ts
src/public/mathfield-element.ts
test/playwright-tests/mouse.spec.ts
test/playwright-tests/physical-keyboard.spec.ts

Fixes context menu Cut functionality for Safari (previously the Cut option from the context menu would do nothing on Safari). Tests have also been added for both keyboard cut/paste shortcuts and also for context menu cut/paste.
The fix checks the return value for `execCommand`, which will be `false` if it fails or is not allowed. In this case, it falls back to manually triggering the cut event.

fix: Safari context menu cut fix

---

CHANGELOG.md
src/core/context-utils.ts
src/core/context.ts
src/core/parser.ts
src/core/types.ts
src/editor-mathfield/mathfield-private.ts
src/editor-mathfield/options.ts
src/latex-commands/environments.ts
src/latex-commands/types.ts
src/public/mathfield-element.ts
src/public/options.ts
test/playwright-test-page/index.html
test/playwright-tests/max-matrix-cols.spec.ts

Currently, the matrix environment only allows 10 columns. This default makes sense since this is the default used by the amsmath library. The amsmath library provides the `MaxMatrixCols` counter to increase this limit. This pull request adds a `maxMatrixCols` property to MathLive fields to allow more than 10 columns in the matrix environment. This property is also exposed as the `max-matrix-cols` attribute.
Sorry about the large diff for `CHANGELOG.md`, I only added the new feature to the top, the linter went to town on the rest of it.

Add maxMatrixCols property so that matrices with more than 10 columns may be defined

---

src/editor-mathfield/mathfield-private.ts

For the callbacks related to persisting focus when switching tabs, this pull request changes from a timeout based approach to cancel the callbacks to a method that looks for change in focus. The timeout based method was not working on Chrome and Firefox in Windows. The new approach still ensures that only the most recent math-field element will have a `visibilitychange` callback associated with it.

fix: persist focus when switching tabs

---

css/mathfield.less
src/common/stylesheet.ts
src/public/mathfield-element.ts

This PR fixes scrolling and cursor position regressions.
- Disable pointer events on `.ML__container` for touch pointers.
- Set cursor position on `pointerup` for touch pointers.
- Move the padding from the host to `.ML__container` to avoid focusing the math field without triggering `pointerdown`.

fix pointer events scroll and cursor position

---

src/editor-mathfield/mathfield-private.ts

This pull request fixes two issues with focus handling when switching away from and back to a tab with a `mathfield` element to make the behavior the same as a standard HTML `input` or `textarea` element. The current behavior is correct when switching tabs (the first test in the two videos below) but doesn't correctly handle the case when switching non-overlapping windows (second test in the two videos below). This was corrected by looking for the window `blur` event rather than the `visibilitychange` event since `visibilitychange` is not triggered when switching windows that are not overlapping.
The second issue that is addressed is correctly handling the case where the user clicks off of the `mathfield` element but doesn't select another element (third test in the videos below, users …

fix: improved refocus behavior on window exit and then return

---

package.json

When importing from `'mathlive/ssr'`, typescript definitions are missing, even though there would be a fitting definition close by.

Add typescript definitions to ssr export

---

package.json

This PR updates subpath exports in the main package.json to comply with Node.js's [subpath patterns](https://nodejs.org/api/packages.html#subpath-patterns), which utilize "direct static matching and replacement."
As a result, it resolves issue #2550, where Mathlive could not be used with Next.js when Turbopack was enabled due to its strict code validation.

Fix package.json subpath exports matching

---

examples/popover-variants-panel/index.html
examples/sticky-variant-panel/index.html
src/api.md
src/public/virtual-keyboard.ts
src/virtual-keyboard/utils.ts
src/virtual-keyboard/variants.ts

fix #2549 
This PR adds a `stickyVariantPanel` option to the VirtualKeyboardKeycap. When this option is enabled, clicking on a key with variants configured will display the Variants Panel without a long press. Additionally, the panel will not automatically hide.
The motivation for implementing this feature is described in #2549, and a similar request can be found in #2363.
- Tests have not been added yet.
- Added an example: sticky-variant-panel/index.html.
- I am not entirely confident about the API naming.

feat: Added option for sticky display of variants panel with a single click

---

css/mathfield.less

Fixed the issue that upon blur prompt box, there was still a surrounding outline box
Fixed result:
https://github.com/user-attachments/assets/bc148bf0-801a-4edc-9acc-66d9eba5eadf

Only show focused prompt box when focused

---

src/public/mathfield-element.ts

When using the virtual keyboard on mobile, typing
quickly would cause a blur event to be dispatched.
This change ignores the blur event in the mathfield
when a touch device is recognized and the virtual
keyboard is visible.
refs: #2254

fix(virtual-keyboard): ignore blur event on touch devices

---

css/mathfield.less

- fix #2577
This pull request addresses the problem highlighted in issue #2577. The `ML__caret` element did not have a defined `display` property and was therefore implicitly treated as `display: inline`. By explicitly setting it to `inline-block`, the rendered formula elements remain static and no longer shift their positions when the caret moves.
I’ve attached videos demonstrating the behavior before and after this fix. Please refer to them for more details.
https://github.com/user-attachments/assets/25b3aab5-5ec1-46d4-8018-46bd6a1f136e
https://github.com/user-attachments/assets/5aadc6e4-b251-4025-94f0-a95fb18aa192

fix: formula text wiggles with caret movement

---

src/latex-commands/definitions-utils.ts

The issues was described in https://github.com/arnog/mathlive/issues/2574
Changes:
-fixed \colonq symbol to use the character `2245` which is the correct equivalent to `:=` (as used on the legacy  \coloneqq according to the current mathtools package: https://ftpmirror1.infania.net/mirror/CTAN/macros/latex/contrib/mathtools/mathtools.pdf

Fixed \coloneq symbol in definitions-utils.ts

---

src/virtual-keyboard/data.ts

Fixes #2590
As shown there, here's the bug:
And here's the fixed screenshot!
Just one line changed 👍

[FIX]: incorrect label for psi on virtual keyboard

---

.github/workflows/playwright.yml
.github/workflows/tests.yml

This PR makes the following updates to GitHub actions YAML files to fix CI errors:
- Lock Ubuntu to 22.04 (playwright browsers have install errors with Ubuntu 24.04)
- Bump upload-artifacts to v4 (v3 is depreciated on GH actions)
- Set node-version to 22 (impacts GH actions only)

ci: fix GitHub actions errors

---

CHANGELOG_2017-2023.md
README.md
documentation/CONTRIBUTOR_GUIDE.md
examples/README.md
examples/basic/README.md
scripts/github-release.sh

The website was updated a few months ago, with all MathLive URLs changing:
* `https://cortexjs.io/mathlive/` → `https://cortexjs.io/mathfield/`
* `https://cortexjs.io/docs/mathlive/` → `https://cortexjs.io/mathfield/api/`
All the old links now return 404, so this PR fixes those links. Would it be possible to also create some redirects from the old URLs?

docs: fix dead links to the cortexjs.io website

---

src/editor-model/delete.ts

This was probably added for debug purposes, but it leaks to apps using mathlive, so it's probably best to remove it now.

fix: remove unnecessary `console.log`

---

src/editor-model/model-private.ts

In my project, I had an error triggered from within MathLive on this line:
`if (this.silenceNotifications || !this.mathfield.host || !this.mathfield)`
The code is pretty clearly trying to bail out if mathfield is absent, but because the check against mathfield is last, the line errors checking mathfield.host first. I swapped the order of the checks so that mathfield is checked first.

Incorrect order of conditions for short-circuting.

---

css/core.less

Resolves #2647, resolves #2634, resolves #2562 
More details on the bug in #2647. As a summary, accents characters (such as \vec → and \hat ˆ) are showing incorrectly due to not using the correct font. 
There is an existing css rule that correctly applies the font only when the accent characters are in a nested span, which only occurs on selection. I've replaced that rule with a more general one that applies to all accents, and removed the obsolete `width: 0` attribute as well.
Other suggestions for solutions are welcome.

Fix: [CSS] Apply correct font to accent body

---

src/editor/keybindings-definitions.ts

Before:
[Screencast from 2025-03-31 13-26-42.webm](https://github.com/user-attachments/assets/569b17aa-571e-4222-b4e6-847e5e932869)
After:
[Screencast from 2025-03-31 13-27-22.webm](https://github.com/user-attachments/assets/204ddebd-cad1-4f0f-9651-8d5a0a636d8d)
I'm unsure if this is desired behavior. Myself and others who have used MathLive expected the Enter or Return key to accept the current suggestion and to leave LaTeX mode.
If undesired, perhaps there is a way to have this behavior? The `keybindings` property appears to be deprecated

Change binding for Enter to accept suggestion and complete LaTeX mode

---

css/mathfield.less

This correctly restores the color of text when a MathField element loses its focus

Fix colored text when MathField loses focus (fixes #2638, fixes #2479)

---

src/ui/menu/menu.ts

Use capture phase to ensure menu receives `pointerup` event before child menu items.
If `pointerdown` + `pointerup` < 120 ms, menu state should be modal
`pointerup` on scrim should hide menu
(Related: https://github.com/arnog/mathlive/pull/2661)

Use capture to determine if context menu should be modal (fixes #2584)

---

css/core.less
css/mathfield.less

When using a high contrast mode, a media mode called "forced-colors" is enabled. It forces most things to be either black or white. LaTeX symbols and the lines from fractions or square roots were invisible.
**Before**
**After**
You can test by going to Dev Tools > ... > More tools > Rendering > Emulate CSS media feature forced-colors > forced-colors: active

Use forced-color-adjust to fix high contrast mode (resolves #2482)

---

css/virtual-keyboard.less

Fixes `--keycap-text-hover` in the virtual keyboard

Fix keycap-text-hover (fix #2526)

---

css/suggestion-popover.less

Add a 'suggestion-zindex' CSS variable.
`keyboard-zindex` defaults to 105, this currently defaults to 100 to set behind the virtual keyboard, however in front of other elements

Add 'suggestion-zindex' variable for suggestion popover (resolve #1579)

---

css/mathfield.less

This enables initial support for text-shadow.
In order to support the feature properly, this change applies a CSS variable called `--text-shadow` instead of using the normal `text-shadow` CSS property. Some elements (such as the upper line of a square root or the dividing line for a fraction) are implemented as blocks rather than text. 
This change applies the `--text-shadow` variable to both `text-shadow` or `box-shadow` depending upon the element to create a uniform appearance

Add --text-shadow support (resolve #2592)

---

src/editor-mathfield/render.ts

In my project, I'm observing errors because mathfield.field is undefined in `mathfield.resizeObserver.unobserve(mathfield.field);` Given that the function already bails if mathfield is undefined, it seems it should do the same in mathfield.field is undefined.

Protect resizeObserver.unobserve call

---

package-lock.json

fixes this error in the pipeline/command line:
```
`npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

fix: allow npm ci to run

---

src/atoms/array.ts

Array.fill calls the function once for the whole array, so if the environment has multiple columns you end up with multiple cells with the same reference which creates multiple carats for input

fix: create separate atoms for each column of a row

---

src/atoms/prompt.ts

This pull requests aims at solving the incorrect spacing in prompts, where the prompt contents are not vertically centered.
The first fix simply adjusts the prompt position with respect to the content, taking into account also the vertical padding.
**With first fix:**
**Without first fix:**
As we can see, after the first fix, the prompts are incorrectly spaced with respect to the fraction line. The second fix addresses this issue:
**With second fix:**
**Without second fix:**

fix: corrected prompt vertical spacing to account for padding
